### ISSUE TITLE
ModuleNotFoundError: No module named 'dcn_v2'

### ISSUE THREAD

**Issue by an99990** [Picsart-AI-Research/SeMask-Segmentation#10]
command i ran

`SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo# python demo.py --config-file ../configs/ade20k/semantic-segmentation/semask_swin/msfapn_maskformer2_semask_swin_large_IN21k_384_bs16_160k_res640.yaml --input ../images/person_bike.jpg --opts MODEL.WEIGHTS ../semask_large_mask2former_msfapn_ade20k.pth`
 
I went to 
`cd ~/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/mask2former/modeling/pixel_decoder/ops/` and did
`python setup.py install`

but it did not solve the import issue
I also did `pip install -requirements.txt`

I took the checkpoint from the README table

Thank you again for any support

**Comment by praeclarumjj3** [comment]
Please build the [`DCNv2`](https://github.com/Picsart-AI-Research/SeMask-Segmentation/tree/main/SeMask-FAPN/DCNv2) model as well.

**Comment by praeclarumjj3** [comment]
I am closing this issue. If you face any problems building the `dcnv2` module, feel free to open this again.
