### ISSUE TITLE
GPU information for every model/variants

### ISSUE THREAD

**Issue by an99990** [Picsart-AI-Research/SeMask-Segmentation#12]
Hi,
I tried running the instance segmentation models and I keep having out of memory issue.
Do you guys have information about needed RAM to run the models ?
Whichever the model I test I get the same allocated ram, is it normal ? 
Here is the log for the model with swin-tiny as backbone
```
RuntimeError: CUDA out of memory. Tried to allocate 7.71 GiB (GPU 0; 8.00 GiB total capacity; 443.31 MiB already allocated; 5.49 GiB free; 478.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
root@39f4c92fa92b:/workspaces/halo-segmentation/halo_segmentation/models/SeMask_Segm
```
thank you

**Comment by praeclarumjj3** [comment]
Hi @an99990, we only train the models for Semantic-Segmentation in this repo. If you have issues with the instance or panoptic segmentation on Mask2Former / MaskFormer, you can open issues in their respective repos.

Anyways, if you have memory issues, you can reduce the batch size in the configuration files. We train our tiny/small models with 4 RTX A6000 GPUs, each having 48 GB of memory. For base/large models, we use 8 RTX A6000 GPUs.

According to my experience, you would need at least 60-80 GB to train a `SeMask-Tiny Mask2Former` with `batch size = 16`.

**Comment by an99990** [comment]
thank you !
