### ISSUE TITLE
cityscapes performance

### ISSUE THREAD

**Issue by ydhongHIT** [Picsart-AI-Research/SeMask-Segmentation#14]
Hi, your result 84.98%mIoU on cityscapes is surprising. Is it the best result or the average result and how about the variance?

**Comment by praeclarumjj3** [comment]
Hey, it is the best result. We trained our model 3 times. The variance was of the order 1e-2 -> std around 0.1.

**Comment by ydhongHIT** [comment]
> Hey, it is the best result. We trained our model 3 times. The variance was of the order 1e-2 -> std around 0.1.

Thanks for your reply. It is amazing that you have so low std on cityscapes. Could you share the 19 categories mIoU of the best result?

**Comment by praeclarumjj3** [comment]
Hey sure. The Detectron2 provides per-class IoU scores only up to one place of decimal, so here are the scores:

| classes       |  IoU |
| --------------|------|
| road          | 98.8 |
| sidewalk      | 89.6 |
| building      | 94.5 |
| wall          | 70.9 |
| fence         | 70.6 |
| pole          | 74.4 |
| traffic light | 78.9 |
| traffic sign  | 85.2 |
| vegetation    | 93.7 |
| terrain       | 69.7 |
| sky           | 95.8 |
| person        | 87.3 |
| rider         | 73.3 |
| car           | 96.4 |
| truck         | 90.6 |
| bus           | 94.8 |
| train         | 89.3 |
| motorcycle    | 77.7 |
| bicycle       | 83.2 |
| **Average**   | 85.0 |
