### ISSUE TITLE
Demo File in the Mask2Performer.

### ISSUE THREAD

**Issue by barbodpj** [Picsart-AI-Research/SeMask-Segmentation#17]
demo.py doesnt exist in the maskformer.

**Comment by praeclarumjj3** [comment]
Hi, please find the demo.py here: https://github.com/Picsart-AI-Research/SeMask-Segmentation/tree/main/SeMask-Mask2Former/demo for Mask2Former.

**Comment by barbodpj** [comment]
sorry, I meant maskformer not mask2former. For mask2former I get this error: 
Please compile MultiScaleDeformableAttention CUDA op with the following commands:
	`cd mask2former/modeling/pixel_decoder/ops`
	`sh make.sh`
but make.sh doesnt exist in that directory.

**Comment by praeclarumjj3** [comment]
Hi, thanks for pointing this out! There was an issue in `.gitignore`. I have pushed the `make.sh` for Mask2Former and `demo` for MaskFormer. Please check again.

**Comment by barbodpj** [comment]
> Hi, thanks for pointing this out! There was an issue in `.gitignore`. I have pushed the `make.sh` for Mask2Former and `demo` for MaskFormer. Please check again.

Thanks, it worked
