### ISSUE TITLE
RecursionError: Caught RecursionError in DataLoader for training with custom dataset

### ISSUE THREAD

**Issue by erenuzyildirim** [Picsart-AI-Research/SeMask-Segmentation#19]
Hi, thank you for sharing this great work. I encounter the RecursionError: maximum recursion depth exceeded while calling a Python object for training with the custom dataset. 

I applied the solution of setting the sys.getrecursionlimit() to a higher value but it doesn't work.

Thanks.

**Comment by praeclarumjj3** [comment]
Hey, which network are you talking about?

**Comment by erenuzyildirim** [comment]
It is Semask-FPN(semfpn_semask_swin)

**Comment by praeclarumjj3** [comment]
Could you post the full log here? It would be more helpful. I assume you followed the official steps mentioned in the [mmsegmentation docs](https://mmsegmentation.readthedocs.io/en/latest/tutorials/customize_datasets.html).

**Comment by erenuzyildirim** [comment]
Yes, I followed the official steps mentioned in the doc. You can find the full log and terminal screen in the below:

[20220311_232208.log](https://github.com/Picsart-AI-Research/SeMask-Segmentation/files/8235484/20220311_232208.log)

![Screenshot from 2022-03-11 23-23-05](https://user-images.githubusercontent.com/72136203/157956397-191b3757-de49-4b5b-9b80-926a2a532e1b.png)

**Comment by praeclarumjj3** [comment]
Could you share the dataset config file and a sample structure of your dataset? Even better if you have pushed the code to a GitHub repo. I will be able to help you better. It looks like an mmsegmentation issue to me.

**Comment by erenuzyildirim** [comment]
I pushed the code files that I updated from your project or newly added. I also pushed  structure of the dataset with three example images for each split.

I have already sent an invitation to you for the repo "Semask-FPN-training-custom-dataset".

Thanks.

**Comment by praeclarumjj3** [comment]
Could you try adding a suffix other than `.png` for the seg map? Since both images and gts contain `.png`, it may be an issue. 
<img width="1216" alt="Screenshot 2022-03-15 at 1 58 39 PM" src="https://user-images.githubusercontent.com/54928629/158336871-7bc780e2-a254-4a5d-8652-7f386635891b.png">

**Comment by erenuzyildirim** [comment]
I changed the suffix of annotation files as ".jpg", but the error still occurs. I upload the log file and I also add the console output to the end of the log file.

Thanks.

**Comment by erenuzyildirim** [comment]
Could you recommend any other solution? Thanks.

**Comment by praeclarumjj3** [comment]
Could you try cloning the original mmsegmentation repo and running any config with your dataset? If that works, then we will know where to look for possible errors, at least.

Thanks

**Comment by erenuzyildirim** [comment]
It doesn't work. You can also try yourself with the sample  images in the repo that I have shared with you.

**Comment by praeclarumjj3** [comment]
Right, it's a core mmsegmentation issue I believe. Why don't you open an issue on the main repo?

**Comment by erenuzyildirim** [comment]
After your recommendation, I cloned the original mmsegmentation repo today and checked it. 

Since SeMask provides training with a custom dataset, even it is based on mmsegmentation, I opened an issue here. I think this is not surprising!
