### ISSUE TITLE
Strange sem-seg resutls

### ISSUE THREAD

**Issue by Shawn207** [Picsart-AI-Research/SeMask-Segmentation#23]
Hi there!
I am trying to test on SeMask-FAPN, by calling:
`python demo.py --config-file ../configs/ade20k/semantic-segmentation/semask_swin/fapn_maskformer2_semask_swin_large_IN21k_384_bs16_160k_res640.yaml --input /workspace/SeMask-Segmentation/images/ADE_val_00001001.jpg --output /workspace/SeMask-Segmentation/output/ --opts MODEL.WEIGHTS /workspace/SeMask-Segmentation/checkpoints/semask_large_mask2former_fapn_ade20k.pth`
and I downloaded pre-trained model from [https://drive.google.com/file/d/1DQ9KltSLDj47H2jYnCtVwyBf7KPR9SM_/view](url)
The result is here:
![adetest](https://user-images.githubusercontent.com/60746163/161656373-d8e84940-877b-4c52-bd94-37fc06d286e1.jpg)

That doesn't make sense. Do you have any idea about where I got things wrong?
Thank you!

**Comment by praeclarumjj3** [comment]
Hi, have you tried testing the SeMask-MsFaPN with its corresponding config file? If that works, the problem would be with the FaPN network, and we will know where to look for issues.

**Comment by Shawn207** [comment]
> Hi, have you tried testing the SeMask-MsFaPN with its corresponding config file? If that works, the problem would be with the FaPN network, and we will know where to look for issues.

Yeah the MS version works fine

**Comment by Shawn207** [comment]
> Hi, have you tried testing the SeMask-MsFaPN with its corresponding config file? If that works, the problem would be with the FaPN network, and we will know where to look for issues.

Hi, could you please let me know if the issue was figured out?
Thanks

**Comment by praeclarumjj3** [comment]
Hi, I have been busy lately so I couldn't look for the possible problem. I will let you know when I take a look at it.

**Comment by Shawn207** [comment]
> Hi, I have been busy lately so I couldn't look for the possible problem. I will let you know when I take a look at it.

Okay, I understand. Thanks

**Comment by praeclarumjj3** [comment]
Hi @Shawn207, sorry for the delay. I have updated the checkpoints. Could you try again?

**Comment by praeclarumjj3** [comment]
I am closing this issue since the demo works fine for me now. Feel free to reopen if you face any more problems.
