### ISSUE TITLE
The data format in the 'instances' field of input

### ISSUE THREAD

**Issue by KombangkoeDias** [Picsart-AI-Research/SeMask-Segmentation#24]
In the code from SeMask-MaskFormer/mask_former/semask_mask_former_model.py, the each input dict in the batch_inputs needs a field 'instances',  I'm not sure what format of data should the x["instances"] in the picture be. I'm doing the semantic segmentation task and all I have are the image and its per-pixel mask so I'm not sure what to add to this instance field.
![image](https://user-images.githubusercontent.com/47164917/164177670-40f8034e-2a9c-489a-9df5-c6fd2768a84c.png)

**Comment by praeclarumjj3** [comment]
Hi @KombangkoeDias, thanks for your interest.

The `instances` attribute for the semantic-segmentation task represents the per-category binary masks for an image: https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/f12cf00c86afe669dfbea1dff0f8053ba49fed56/SeMask-MaskFormer/mask_former/data/dataset_mappers/mask_former_semantic_dataset_mapper.py#L161-L182

As I understand from your description, you have the images and gt, so the dataset mapper will itself take care of defining the instances. You might have to create a custom dataset class following the [detectron2 instructions](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html), though.
https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/f12cf00c86afe669dfbea1dff0f8053ba49fed56/SeMask-MaskFormer/configs/ade20k-150/Base-ADE20K-150.yaml#L48

**Comment by KombangkoeDias** [comment]
Thank you, that helps. I can start training now.
