### ISSUE TITLE
encounter errors when running demo.py 

### ISSUE THREAD

**Issue by fjremnav** [Picsart-AI-Research/SeMask-Segmentation#25]
When I run the following demo.py command:
python demo.py --config-file ../configs/cityscapes/semantic-segmentation/semask_swin/maskformer2_semask_swin_large_IN21k_384_bs16_90k.yaml --input ../../../Hybr
idNets/images/lane1.jpg --opts MODEL.WEIGHTS ../weights/semask_large_mask2former_cityscapes.pth

I got the following errors;

Traceback (most recent call last):
  File "demo.py", line 106, in <module>
    cfg = setup_cfg(args)
  File "demo.py", line 38, in setup_cfg
    add_maskformer2_config(cfg)
  File "/home/user/4TB/test_tmp/git/SeMask-Segmentation/SeMask-Mask2Former/demo/../mask2former/config.py", line 85, in add_maskformer2_config
    cfg.MODEL.SWIN.QK_SCALE = None
  File "/home/test/anaconda3/envs/remnav/lib/python3.7/site-packages/fvcore/common/config.py", line 148, in __setattr__
    super().__setattr__(name, val)
  File "/home/test/anaconda3/envs/remnav/lib/python3.7/site-packages/yacs/config.py", line 158, in __setattr__
    type(value), name, _VALID_TYPES
  File "/home/test/anaconda3/envs/remnav/lib/python3.7/site-packages/yacs/config.py", line 525, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key QK_SCALE; valid types = {<class 'str'>, <class 'int'>, <class 'bool'>, <class 'tuple'>, <class 'list'>, <class 'float'>}

Any idea How to fix it?

Thanks,

**Comment by praeclarumjj3** [comment]
Hi @fjremnav, thanks for your interest in our work.

I am unable to reproduce the error on my end. I run the following command, which gives me the correct output. One possible reason could be that you use `python 3.7`. We tested our code with [`python >= 3.8`](https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/main/SeMask-Mask2Former/README.md#installation). You may also want to take a look at [this issue](https://github.com/facebookresearch/detectron2/issues/3649) that hints of a version related problem.

```.python
python demo/demo.py --config-file configs/cityscapes/semantic-segmentation/semask_swin/maskformer2_semask_swin_large_IN21k_384_bs16_90k.yaml --input /home/datasets/cityscapes/leftImg8bit/val/frankfurt/frankfurt_000000_000294_leftImg8bit.png --output res.png --opts MODEL.WEIGHTS semask_large_mask2former_cityscapes.pth 
```

I am attaching a sample input/output which worked for us for your reference.

![frankfurt_000000_000294_leftImg8bit](https://user-images.githubusercontent.com/54928629/165050665-8d2beef8-eeab-435e-b5e5-af2116538879.png)
![res](https://user-images.githubusercontent.com/54928629/165050674-5f1d1700-7bcc-4b37-8c59-b0d76340df70.png)

**Comment by fjremnav** [comment]
>>pip uninstall yacs
>>pip install yacs --upgrade

This fixes the issue.
Thanks,
