### ISSUE TITLE
the comparison with sota results

### ISSUE THREAD

**Issue by ydhongHIT** [Picsart-AI-Research/SeMask-Segmentation#3]
How about the result comparison under the same training setting?

**Comment by praeclarumjj3** [comment]
@ydhongHIT We compare the results of our SeMask framework with the baselines under the same training setting as used in the baseline experiments. It is one of the factors which makes SeMask efficient. We don't need to alter any settings.

**Comment by ydhongHIT** [comment]
> @ydhongHIT We compare the results of our SeMask framework with the baselines under the same training setting as used in the baseline experiments. It is one of the factors which makes SeMask efficient. We don't need to alter any settings.

Thanks for the reply! I understand that you keep the same setting in the baseline experiments. But when comparing with the sota mask2former, the training setting is different from the original paper.

**Comment by praeclarumjj3** [comment]
@ydhongHIT Could you point out the difference? We use the same settings as done in the original [Mask2Former](https://github.com/facebookresearch/Mask2Former) repo. You may compare the [semask-swin config](https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/main/SeMask-Mask2Former/configs/ade20k/semantic-segmentation/semask_swin/maskformer2_semask_swin_large_IN21k_384_bs16_160k_res640.yaml) and [swin config](https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/main/SeMask-Mask2Former/configs/ade20k/semantic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_160k_res640.yaml). We don't modify anything but the backbone and decoder head.

**Comment by ydhongHIT** [comment]
> 
I only read the papers rather than the codes. I will compare the codes, thanks.

**Comment by ydhongHIT** [comment]
> @ydhongHIT Could you point out the difference? We use the same settings as done in the original [Mask2Former](https://github.com/facebookresearch/Mask2Former) repo. You may compare the [semask-swin config](https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/main/SeMask-Mask2Former/configs/ade20k/semantic-segmentation/semask_swin/maskformer2_semask_swin_large_IN21k_384_bs16_160k_res640.yaml) and [swin config](https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/main/SeMask-Mask2Former/configs/ade20k/semantic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_160k_res640.yaml). We don't modify anything but the backbone and decoder head.

I only read the papers rather than the codes. I will compare the codes, thanks.
