### ISSUE TITLE
how to build the DCNv2 module and Detectron2

### ISSUE THREAD

**Issue by wzy1026wzy** [Picsart-AI-Research/SeMask-Segmentation#30]
the [DCNv2](https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/main/SeMask-FAPN/DCNv2) module  is compatible with [Pytorch v1.7.1](https://pytorch.org/get-started/locally/), but the  Detectron2 hope PyTorch ≥ 1.8(https://detectron2.readthedocs.io/en/latest/tutorials/install.html). How to slove the conflict？

**Comment by praeclarumjj3** [comment]
Hi @wzy1026wzy, please install [Detectron2 v0.5](https://github.com/facebookresearch/detectron2/releases/tag/v0.5)

**Comment by wzy1026wzy** [comment]
Thanks a lot. I have solved this problem with your help.

> Hi @wzy1026wzy, please install [Detectron2 v0.5](https://github.com/facebookresearch/detectron2/releases/tag/v0.5)
