### ISSUE TITLE
Great work！ How did the pixel-wise attention maps (Figure I) in the latest paper generated?

### ISSUE THREAD

**Issue by BossZard** [Picsart-AI-Research/SeMask-Segmentation#31]

**Comment by praeclarumjj3** [comment]
Hi @BossZard, thanks for your interest in our work. We compute the similarity maps using the following steps:

- We sample the pixel at the red cross sign.
- We calculate the pixel-wise similarity of that pixel value to the feature map using matrix multiplication operation. You can broadcast the single pixel value to the feature map's shape.

```python
def save_image_grid(feat, fname,):
    x, y = 625, 600
    feat = feat[0].astype(np.uint8)

    C, H, W = feat.shape
    
    v = np.expand_dims(feat[:, y, x], axis=1)
    feat = feat.reshape(C, H*W)
    norm = np.linalg.norm(feat, axis=0)
    feat = feat / norm
    v = np.transpose(v, (1,0))
    feats = np.einsum('mn,nd->dm', v, feat)
    feats = feats.reshape(H, W)

    plt.imsave(fname + '.png', feats)
```

<img width="709" alt="Screenshot 2022-10-03 at 3 47 38 PM" src="https://user-images.githubusercontent.com/54928629/193699319-6b66417f-5501-41a9-a9b1-9a814a269daf.png">

**Comment by BossZard** [comment]
Thank you very much for your reply. In addition, can the Semantic Query variable be understood as a more accurate query? That is, help the pixels to focus more on the same category of pixels in the attention map?

**Comment by praeclarumjj3** [comment]
Hi @BossZard, you are partly correct. When we calculate the segmentation score using a semantic query, we are trying to focus more on features that belong to the semantic classes in the dataset.

**Comment by BossZard** [comment]
Thanks!
