### ISSUE TITLE
Will you provide pre training weights

### ISSUE THREAD

**Issue by Joysheng** [Picsart-AI-Research/SeMask-Segmentation#4]

**Comment by praeclarumjj3** [comment]
@Joysheng You may download the pretrained models for each framework, following the corresponding instructions:

- SeMask FPN: [Swin Weights, 2<sup>nd</sup> point under results](https://github.com/Picsart-AI-Research/SeMask-Segmentation/tree/main/SeMask-FPN#1-results)
- SeMask Mask2Former: [ImageNet Pretrained Models](https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/main/SeMask-Mask2Former/MODEL_ZOO.md#third-party-imagenet-pretrained-models)
- SeMask MaskFormer: [ImageNet Pretrained Models](https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/main/SeMask-MaskFormer/MODEL_ZOO.md#third-party-imagenet-pretrained-models)
