### ISSUE TITLE
About DCN Module

### ISSUE THREAD

**Issue by hardyho** [Picsart-AI-Research/SeMask-Segmentation#5]
I'm running make.sh to install DCN module and encounter following errors:
```
identifier "THCudaBlas_SgemmBatched" is undefined
identifier "THCudaBlas_Sgemm" is undefined
```
This problem could be solved by running under pytorch1.7, however pytorch1.9 is required for Mask2Former. How to solve this problem? Thanks!

**Comment by praeclarumjj3** [comment]
Hi @hardyho, we use PyTorch 1.7.1 for running experiments with the FaPN incorporated into our models. If you try running our code with PyTorch 1.7, it should work,

**Comment by hardyho** [comment]
Thanks! It works now.
