### ISSUE TITLE
Questions about Inference size

### ISSUE THREAD

**Issue by caihaunqai** [Picsart-AI-Research/SeMask-Segmentation#6]
Hello, thank you for your excellent job. After reading your paper, I wonder how to resize the mage to a fixed input size.  The paper illustrates that to handle varying image sizes during inference, we keep the aspect ratio intact and resize the image to a resolution with the smaller edge resized to the training resolution.   In order to keep the aspect ratio the same, do we resize the longer side to the training size and padding the shorter side? If not, how can we keep the aspect ratio the same?

**Comment by praeclarumjj3** [comment]
Hi @caihaunqai, thanks for the praise. The shorter edge of the image is resized based on the scale passed during inference. You may refer to the [transforms.py](https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/main/SeMask-FPN/mmseg/datasets/pipelines/transforms.py) file for better understanding. There is also an attribute named [`keep_ratio`](https://github.com/Picsart-AI-Research/SeMask-Segmentation/blob/786f395fab4e156970628134cb49eb3547d7287b/SeMask-FPN/mmseg/datasets/pipelines/transforms.py#L37) which is set to `True` during inference, so take care of that while looking at `transforms.py.` Regardless, the final prediction is resized to the original image size before calculating the `mIoU` score.
